// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDHUcH_13novhNfa621v_KKGkqcThg5Mw',
    appId: '1:894920769523:web:94d272e70e7842646a9c86',
    messagingSenderId: '894920769523',
    projectId: 'fir-sample-app-d3f8b',
    authDomain: 'fir-sample-app-d3f8b.firebaseapp.com',
    storageBucket: 'fir-sample-app-d3f8b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNBHEJJIbTTsX7M70WtMVkhpi9NEJibSo',
    appId: '1:894920769523:android:345df9bedd86b3916a9c86',
    messagingSenderId: '894920769523',
    projectId: 'fir-sample-app-d3f8b',
    storageBucket: 'fir-sample-app-d3f8b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAs6PjkxazkGsBdWyoIZ82JrKVhz-YViCM',
    appId: '1:894920769523:ios:6a8841b52176cef76a9c86',
    messagingSenderId: '894920769523',
    projectId: 'fir-sample-app-d3f8b',
    storageBucket: 'fir-sample-app-d3f8b.appspot.com',
    iosBundleId: 'com.example.chatDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAs6PjkxazkGsBdWyoIZ82JrKVhz-YViCM',
    appId: '1:894920769523:ios:da58a8d199b876796a9c86',
    messagingSenderId: '894920769523',
    projectId: 'fir-sample-app-d3f8b',
    storageBucket: 'fir-sample-app-d3f8b.appspot.com',
    iosBundleId: 'com.example.chatDemo.RunnerTests',
  );
}
